# Auto-generated by tools/gen_ctypes.py. Do not edit by hand.

from __future__ import annotations

import ctypes
from typing import Protocol

from . import config, util


class _LibProvider(Protocol):
    def lib(self, name: str) -> ctypes.CDLL: ...


def configure(bridge: _LibProvider) -> None:
    """Attach argtypes/restype to every loaded module's KITH_API surface."""
    util.configure(bridge.lib("util"))
    config.configure(bridge.lib("config"))
