# Auto-generated by tools/gen_ctypes.py. Do not edit by hand.

from __future__ import annotations

import contextlib
import ctypes
from typing import Protocol

from . import (
    aoi,
    config,
    control,
    coord,
    db,
    fabric,
    gateway,
    logger,
    metrics,
    net,
    proto,
    reactor,
    sim,
    state,
    util,
    worker,
)


class _LibProvider(Protocol):
    def lib(self, name: str) -> ctypes.CDLL: ...


def configure(bridge: _LibProvider) -> None:
    """Attach argtypes/restype to every loaded module's KITH_API surface."""
    util.configure(bridge.lib("util"))
    config.configure(bridge.lib("config"))
    logger.configure(bridge.lib("logger"))
    metrics.configure(bridge.lib("metrics"))
    proto.configure(bridge.lib("proto"))
    sim.configure(bridge.lib("sim"))
    aoi.configure(bridge.lib("aoi"))
    fabric.configure(bridge.lib("fabric"))
    net.configure(bridge.lib("net"))
    reactor.configure(bridge.lib("reactor"))
    worker.configure(bridge.lib("worker"))
    state.configure(bridge.lib("state"))
    db.configure(bridge.lib("db"))
    with contextlib.suppress(OSError):
        control.configure(bridge.lib("control"))
    coord.configure(bridge.lib("coord"))
    gateway.configure(bridge.lib("gateway"))
