# Auto-generated by tools/gen_ctypes.py. Do not edit by hand.

from __future__ import annotations

import ctypes
from typing import Protocol

from . import config, logger, metrics, net, proto, util


class _LibProvider(Protocol):
    def lib(self, name: str) -> ctypes.CDLL: ...


def configure(bridge: _LibProvider) -> None:
    """Attach argtypes/restype to every loaded module's KITH_API surface."""
    util.configure(bridge.lib("util"))
    config.configure(bridge.lib("config"))
    logger.configure(bridge.lib("logger"))
    metrics.configure(bridge.lib("metrics"))
    proto.configure(bridge.lib("proto"))
    net.configure(bridge.lib("net"))
