# Auto-generated by tools/gen_ctypes.py from:
#   kith/aoi/aoi.h
# Regenerate via `python3 tools/gen_ctypes.py`. Do not edit by hand.


from __future__ import annotations

import ctypes
from enum import IntEnum

from kith._generated.types import kith_allocator_t


class kith_aoi(ctypes.Structure):
    pass


kith_aoi_t = kith_aoi


class kith_aoi_params(ctypes.Structure):
    pass


kith_aoi_params_t = kith_aoi_params


class kith_aoi_object(ctypes.Structure):
    pass


kith_aoi_object_t = kith_aoi_object


class kith_aoi_sphere(ctypes.Structure):
    pass


kith_aoi_sphere_t = kith_aoi_sphere


class kith_aoi_box(ctypes.Structure):
    pass


kith_aoi_box_t = kith_aoi_box


class kith_aoi_format(IntEnum):
    KITH_AOI_FIX_SHIFT = 16


class kith_aoi_default(IntEnum):
    KITH_AOI_DEFAULT_BUCKET_COUNT = 4096
    KITH_AOI_DEFAULT_CELL_SIZE = 1048576
    KITH_AOI_MAX_BUCKET_COUNT = 2147483648


kith_aoi_visit_fn = ctypes.CFUNCTYPE(
    ctypes.c_bool, ctypes.POINTER(kith_aoi_object), ctypes.c_void_p
)

kith_aoi_params._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("cell_size", ctypes.c_int64),
    ("bucket_count", ctypes.c_uint32),
    ("pad", ctypes.c_uint32),
    ("reserved", ctypes.c_void_p * 8),
]

kith_aoi_object._fields_ = [
    ("id", ctypes.c_uint64),
    ("pos_x", ctypes.c_int64),
    ("pos_y", ctypes.c_int64),
    ("pos_z", ctypes.c_int64),
    ("radius", ctypes.c_int64),
    ("user_ptr", ctypes.c_void_p),
]

kith_aoi_sphere._fields_ = [
    ("cx", ctypes.c_int64),
    ("cy", ctypes.c_int64),
    ("cz", ctypes.c_int64),
    ("radius", ctypes.c_int64),
]

kith_aoi_box._fields_ = [
    ("min_x", ctypes.c_int64),
    ("min_y", ctypes.c_int64),
    ("min_z", ctypes.c_int64),
    ("max_x", ctypes.c_int64),
    ("max_y", ctypes.c_int64),
    ("max_z", ctypes.c_int64),
]

# ---------------------------------------------------------------------------
# function signatures
# ---------------------------------------------------------------------------
_FUNCTIONS: list[tuple[str, object, list[object]]] = [
    (
        "kith_aoi_create",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_aoi_params_t),
            ctypes.POINTER(kith_allocator_t),
            ctypes.POINTER(ctypes.POINTER(kith_aoi_t)),
        ],
    ),
    ("kith_aoi_destroy", None, [ctypes.POINTER(kith_aoi_t)]),
    (
        "kith_aoi_insert",
        ctypes.c_int,
        [ctypes.POINTER(kith_aoi_t), ctypes.POINTER(kith_aoi_object_t)],
    ),
    (
        "kith_aoi_update",
        ctypes.c_int,
        [ctypes.POINTER(kith_aoi_t), ctypes.POINTER(kith_aoi_object_t)],
    ),
    ("kith_aoi_remove", ctypes.c_int, [ctypes.POINTER(kith_aoi_t), ctypes.c_uint64]),
    (
        "kith_aoi_lookup",
        ctypes.c_int,
        [ctypes.POINTER(kith_aoi_t), ctypes.c_uint64, ctypes.POINTER(kith_aoi_object_t)],
    ),
    (
        "kith_aoi_query_sphere",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_aoi_t),
            ctypes.POINTER(kith_aoi_sphere_t),
            kith_aoi_visit_fn,
            ctypes.c_void_p,
        ],
    ),
    (
        "kith_aoi_query_box",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_aoi_t),
            ctypes.POINTER(kith_aoi_box_t),
            kith_aoi_visit_fn,
            ctypes.c_void_p,
        ],
    ),
    ("kith_aoi_size", ctypes.c_size_t, [ctypes.POINTER(kith_aoi_t)]),
]


def configure(lib: ctypes.CDLL) -> None:
    """Attach argtypes/restype to every KITH_API symbol on `lib`."""
    for name, restype, argtypes in _FUNCTIONS:
        fn = getattr(lib, name)
        fn.restype = restype
        fn.argtypes = argtypes
