# Auto-generated by tools/gen_ctypes.py from:
#   kith/client/client.h
# Regenerate via `python3 tools/gen_ctypes.py`. Do not edit by hand.


from __future__ import annotations

import ctypes
from enum import IntEnum

from kith._generated.logger import kith_logger_t
from kith._generated.proto import kith_proto_frame, kith_proto_frame_t, kith_proto_t
from kith._generated.types import kith_allocator_t


class kith_client(ctypes.Structure):
    pass


kith_client_t = kith_client


class kith_client_bootstrap_step(ctypes.Structure):
    pass


kith_client_bootstrap_step_t = kith_client_bootstrap_step


class kith_client_command(ctypes.Structure):
    pass


kith_client_command_t = kith_client_command


class kith_client_event(ctypes.Structure):
    pass


kith_client_event_t = kith_client_event


class kith_client_params(ctypes.Structure):
    pass


kith_client_params_t = kith_client_params


class kith_client_bootstrap_status(ctypes.Structure):
    pass


kith_client_bootstrap_status_t = kith_client_bootstrap_status


class kith_client_runtime_status(ctypes.Structure):
    pass


kith_client_runtime_status_t = kith_client_runtime_status


class kith_client_default(IntEnum):
    KITH_CLIENT_DEFAULT_OUTBOUND_CAP = 64
    KITH_CLIENT_DEFAULT_EVENT_CAP = 256
    KITH_CLIENT_DEFAULT_PING_INTERVAL_MS = 1000
    KITH_CLIENT_DEFAULT_RECONNECT_BASE_MS = 250
    KITH_CLIENT_DEFAULT_RECONNECT_MAX_MS = 4000


class kith_client_format(IntEnum):
    KITH_CLIENT_EVENT_PAYLOAD_MAX = 1024


class kith_client_bootstrap_state(IntEnum):
    KITH_CLIENT_BOOTSTRAP_IDLE = 0
    KITH_CLIENT_BOOTSTRAP_RUNNING = 1
    KITH_CLIENT_BOOTSTRAP_READY = 2
    KITH_CLIENT_BOOTSTRAP_FAILED = 3


kith_client_bootstrap_state_t = kith_client_bootstrap_state

kith_client_step_enter_fn = ctypes.CFUNCTYPE(
    ctypes.c_int,
    ctypes.POINTER(kith_client),
    ctypes.c_void_p,
    ctypes.POINTER(ctypes.c_uint16),
    ctypes.POINTER(ctypes.c_uint8),
    ctypes.c_uint,
    ctypes.POINTER(ctypes.c_uint),
)

kith_client_step_reply_fn = ctypes.CFUNCTYPE(
    ctypes.c_int,
    ctypes.POINTER(kith_client),
    ctypes.c_void_p,
    ctypes.POINTER(kith_proto_frame),
    ctypes.POINTER(ctypes.c_uint),
)

kith_client_frame_fn = ctypes.CFUNCTYPE(
    None, ctypes.POINTER(kith_client), ctypes.c_void_p, ctypes.POINTER(kith_proto_frame)
)

kith_client_bootstrap_step._fields_ = [
    ("await_type_id", ctypes.c_uint16),
    ("on_enter", kith_client_step_enter_fn),
    ("on_reply", kith_client_step_reply_fn),
    ("ctx", ctypes.c_void_p),
]

kith_client_command._fields_ = [
    ("type_id", ctypes.c_uint16),
    ("flags", ctypes.c_uint8),
    ("correlation_id", ctypes.c_uint64),
    ("payload", ctypes.c_void_p),
    ("payload_len", ctypes.c_uint32),
]

kith_client_event._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("ts_mono_ns", ctypes.c_uint64),
    ("type_id", ctypes.c_uint16),
    ("payload_len", ctypes.c_uint32),
    ("payload", ctypes.c_uint8 * 1024),
    ("reserved", ctypes.c_void_p * 8),
]

kith_client_params._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("outbound_cap", ctypes.c_uint32),
    ("event_cap", ctypes.c_uint32),
    ("ping_type_id", ctypes.c_uint16),
    ("pong_type_id", ctypes.c_uint16),
    ("ping_interval_ms", ctypes.c_uint32),
    ("reconnect_base_ms", ctypes.c_uint32),
    ("reconnect_max_ms", ctypes.c_uint32),
    ("reconnect_max_attempts", ctypes.c_uint32),
    ("reserved", ctypes.c_void_p * 8),
]

kith_client_bootstrap_status._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("state", ctypes.c_uint32),
    ("current_step", ctypes.c_uint32),
    ("step_count", ctypes.c_uint32),
    ("reserved", ctypes.c_void_p * 8),
]

kith_client_runtime_status._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("connected", ctypes.c_uint8),
    ("awaiting_pong", ctypes.c_uint8),
    ("reconnect_due", ctypes.c_uint8),
    ("reserved_u8", ctypes.c_uint8),
    ("reconnect_attempts", ctypes.c_uint32),
    ("rtt_last_ms", ctypes.c_uint32),
    ("rtt_min_ms", ctypes.c_uint32),
    ("rtt_max_ms", ctypes.c_uint32),
    ("rtt_sum_ms", ctypes.c_uint64),
    ("rtt_samples", ctypes.c_uint32),
    ("reserved_u32", ctypes.c_uint32),
    ("last_ping_sent_ms", ctypes.c_uint64),
    ("next_ping_due_ms", ctypes.c_uint64),
    ("next_reconnect_due_ms", ctypes.c_uint64),
    ("reserved", ctypes.c_void_p * 8),
]

# ---------------------------------------------------------------------------
# function signatures
# ---------------------------------------------------------------------------
_FUNCTIONS: list[tuple[str, object, list[object]]] = [
    (
        "kith_client_create",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_client_params_t),
            ctypes.POINTER(kith_proto_t),
            ctypes.POINTER(kith_logger_t),
            ctypes.POINTER(kith_allocator_t),
            ctypes.POINTER(ctypes.POINTER(kith_client_t)),
        ],
    ),
    ("kith_client_destroy", None, [ctypes.POINTER(kith_client_t)]),
    (
        "kith_client_configure_bootstrap",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_client_t),
            ctypes.POINTER(kith_client_bootstrap_step_t),
            ctypes.c_uint32,
        ],
    ),
    (
        "kith_client_set_frame_handler",
        None,
        [ctypes.POINTER(kith_client_t), kith_client_frame_fn, ctypes.c_void_p],
    ),
    ("kith_client_on_connected", ctypes.c_int, [ctypes.POINTER(kith_client_t), ctypes.c_uint64]),
    ("kith_client_on_disconnected", ctypes.c_int, [ctypes.POINTER(kith_client_t), ctypes.c_uint64]),
    (
        "kith_client_on_connect_failed",
        ctypes.c_int,
        [ctypes.POINTER(kith_client_t), ctypes.c_uint64],
    ),
    (
        "kith_client_feed_frame",
        ctypes.c_int,
        [ctypes.POINTER(kith_client_t), ctypes.POINTER(kith_proto_frame_t), ctypes.c_uint64],
    ),
    (
        "kith_client_pop_outbound",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_client_t),
            ctypes.POINTER(ctypes.c_uint8),
            ctypes.c_uint32,
            ctypes.POINTER(ctypes.c_uint32),
        ],
    ),
    (
        "kith_client_submit_interactive",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_client_t),
            ctypes.POINTER(kith_client_command_t),
            ctypes.POINTER(ctypes.c_uint64),
        ],
    ),
    (
        "kith_client_publish_event",
        ctypes.c_int,
        [ctypes.POINTER(kith_client_t), ctypes.POINTER(kith_client_event_t)],
    ),
    (
        "kith_client_drain_events",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_client_t),
            ctypes.POINTER(kith_client_event_t),
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_size_t),
        ],
    ),
    ("kith_client_tick", ctypes.c_int, [ctypes.POINTER(kith_client_t), ctypes.c_uint64]),
    (
        "kith_client_bootstrap_status",
        ctypes.c_int,
        [ctypes.POINTER(kith_client_t), ctypes.POINTER(kith_client_bootstrap_status_t)],
    ),
    (
        "kith_client_runtime_status",
        ctypes.c_int,
        [ctypes.POINTER(kith_client_t), ctypes.POINTER(kith_client_runtime_status_t)],
    ),
]


def configure(lib: ctypes.CDLL) -> None:
    """Attach argtypes/restype to every KITH_API symbol on `lib`."""
    for name, restype, argtypes in _FUNCTIONS:
        fn = getattr(lib, name)
        fn.restype = restype
        fn.argtypes = argtypes
