# Auto-generated by tools/gen_ctypes.py from:
#   kith/config/config.h
# Regenerate via `python3 tools/gen_ctypes.py`. Do not edit by hand.


from __future__ import annotations

import ctypes

from kith._generated.types import kith_allocator_t


class kith_config(ctypes.Structure):
    pass


kith_config_t = kith_config


class kith_config_params(ctypes.Structure):
    pass


kith_config_params_t = kith_config_params

kith_config_params._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("env_prefix", ctypes.c_char_p),
    ("file_path", ctypes.c_char_p),
    ("reserved", ctypes.c_void_p * 8),
]

# ---------------------------------------------------------------------------
# function signatures
# ---------------------------------------------------------------------------
_FUNCTIONS: list[tuple[str, object, list[object]]] = [
    (
        "kith_config_create",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_config_params_t),
            ctypes.POINTER(kith_allocator_t),
            ctypes.POINTER(ctypes.POINTER(kith_config_t)),
        ],
    ),
    ("kith_config_destroy", None, [ctypes.POINTER(kith_config_t)]),
    ("kith_config_has", ctypes.c_bool, [ctypes.POINTER(kith_config_t), ctypes.c_char_p]),
    (
        "kith_config_string",
        ctypes.c_int,
        [ctypes.POINTER(kith_config_t), ctypes.c_char_p, ctypes.POINTER(ctypes.c_char_p)],
    ),
    (
        "kith_config_bool",
        ctypes.c_int,
        [ctypes.POINTER(kith_config_t), ctypes.c_char_p, ctypes.POINTER(ctypes.c_bool)],
    ),
    (
        "kith_config_u16",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_config_t),
            ctypes.c_char_p,
            ctypes.c_uint16,
            ctypes.c_uint16,
            ctypes.POINTER(ctypes.c_uint16),
        ],
    ),
    (
        "kith_config_u32",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_config_t),
            ctypes.c_char_p,
            ctypes.c_uint32,
            ctypes.c_uint32,
            ctypes.POINTER(ctypes.c_uint32),
        ],
    ),
    (
        "kith_config_u64",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_config_t),
            ctypes.c_char_p,
            ctypes.c_uint64,
            ctypes.c_uint64,
            ctypes.POINTER(ctypes.c_uint64),
        ],
    ),
]


def configure(lib: ctypes.CDLL) -> None:
    """Attach argtypes/restype to every KITH_API symbol on `lib`."""
    for name, restype, argtypes in _FUNCTIONS:
        fn = getattr(lib, name)
        fn.restype = restype
        fn.argtypes = argtypes
