# Auto-generated by tools/gen_ctypes.py from:
#   kith/control/control.h
# Regenerate via `python3 tools/gen_ctypes.py`. Do not edit by hand.


from __future__ import annotations

import ctypes
from enum import IntEnum

from kith._generated.logger import kith_logger_t
from kith._generated.metrics import kith_metrics_t
from kith._generated.reactor import kith_reactor_t
from kith._generated.types import kith_allocator_t
from kith._generated.worker import kith_worker_t


class kith_control(ctypes.Structure):
    pass


kith_control_t = kith_control


class kith_control_header(ctypes.Structure):
    pass


kith_control_header_t = kith_control_header


class kith_control_request(ctypes.Structure):
    pass


kith_control_request_t = kith_control_request


class kith_control_response(ctypes.Structure):
    pass


kith_control_response_t = kith_control_response


class kith_control_route(ctypes.Structure):
    pass


kith_control_route_t = kith_control_route


class kith_control_event(ctypes.Structure):
    pass


kith_control_event_t = kith_control_event


class kith_control_params(ctypes.Structure):
    pass


kith_control_params_t = kith_control_params


class kith_control_default(IntEnum):
    KITH_CONTROL_DEFAULT_PORT = 8080
    KITH_CONTROL_DEFAULT_MAX_CONNECTIONS = 64
    KITH_CONTROL_DEFAULT_READ_BUF = 4096
    KITH_CONTROL_DEFAULT_WRITE_BUF = 262144
    KITH_CONTROL_DEFAULT_EVENT_BUS_CAP = 4096
    KITH_CONTROL_DEFAULT_SSE_FLUSH_MS = 100


class kith_control_method(IntEnum):
    KITH_CONTROL_METHOD_GET = 0
    KITH_CONTROL_METHOD_POST = 1
    KITH_CONTROL_METHOD_PUT = 2
    KITH_CONTROL_METHOD_DELETE = 3
    KITH_CONTROL_METHOD_UNKNOWN = 4


kith_control_method_t = kith_control_method


class kith_control_route_flag(IntEnum):
    KITH_CONTROL_ROUTE_NONE = 0
    KITH_CONTROL_ROUTE_PYTHON = 1


kith_control_route_flag_t = kith_control_route_flag

kith_control_handler_fn = ctypes.CFUNCTYPE(
    ctypes.c_int,
    ctypes.POINTER(kith_control_request),
    ctypes.POINTER(kith_control_response),
    ctypes.c_void_p,
)

kith_control_header._fields_ = [
    ("name", ctypes.c_char_p),
    ("value", ctypes.c_char_p),
]

kith_control_request._fields_ = [
    ("method", ctypes.c_uint32),
    ("path", ctypes.c_char_p),
    ("headers", ctypes.POINTER(kith_control_header_t)),
    ("header_count", ctypes.c_uint32),
    ("body", ctypes.c_void_p),
    ("body_len", ctypes.c_uint32),
]

kith_control_response._fields_ = [
    ("buf", ctypes.POINTER(ctypes.c_uint8)),
    ("cap", ctypes.c_uint32),
    ("len", ctypes.c_uint32),
    ("sse", ctypes.c_bool),
]

kith_control_route._fields_ = [
    ("method", ctypes.c_char_p),
    ("path", ctypes.c_char_p),
    ("handler", kith_control_handler_fn),
    ("ctx", ctypes.c_void_p),
    ("flags", ctypes.c_uint32),
]

kith_control_event._fields_ = [
    ("ts_mono_ns", ctypes.c_uint64),
    ("type", ctypes.c_char_p),
    ("correlation_id", ctypes.POINTER(ctypes.c_uint8)),
    ("payload", ctypes.c_void_p),
    ("payload_len", ctypes.c_uint32),
]

kith_control_params._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("host", ctypes.c_char_p),
    ("port", ctypes.c_uint16),
    ("max_connections", ctypes.c_uint32),
    ("read_buffer_cap", ctypes.c_uint32),
    ("write_buffer_cap", ctypes.c_uint32),
    ("event_bus_cap", ctypes.c_uint32),
    ("sse_flush_ms", ctypes.c_uint32),
    ("reserved", ctypes.c_void_p * 8),
]

# ---------------------------------------------------------------------------
# function signatures
# ---------------------------------------------------------------------------
_FUNCTIONS: list[tuple[str, object, list[object]]] = [
    (
        "kith_control_create",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_control_params_t),
            ctypes.POINTER(kith_reactor_t),
            ctypes.POINTER(kith_logger_t),
            ctypes.POINTER(kith_metrics_t),
            ctypes.POINTER(kith_allocator_t),
            ctypes.POINTER(ctypes.POINTER(kith_control_t)),
        ],
    ),
    ("kith_control_destroy", None, [ctypes.POINTER(kith_control_t)]),
    ("kith_control_start", ctypes.c_int, [ctypes.POINTER(kith_control_t)]),
    ("kith_control_stop", None, [ctypes.POINTER(kith_control_t)]),
    ("kith_control_listen_port", ctypes.c_uint16, [ctypes.POINTER(kith_control_t)]),
    (
        "kith_control_subscriber_count",
        ctypes.c_int,
        [ctypes.POINTER(kith_control_t), ctypes.POINTER(ctypes.c_uint32)],
    ),
    (
        "kith_control_attach_worker_pool",
        ctypes.c_int,
        [ctypes.POINTER(kith_control_t), ctypes.POINTER(kith_worker_t)],
    ),
    (
        "kith_control_register_route",
        ctypes.c_int,
        [ctypes.POINTER(kith_control_t), ctypes.POINTER(kith_control_route_t)],
    ),
    (
        "kith_control_publish_event",
        ctypes.c_int,
        [ctypes.POINTER(kith_control_t), ctypes.POINTER(kith_control_event_t)],
    ),
    (
        "kith_control_response_status",
        ctypes.c_int,
        [ctypes.POINTER(kith_control_response_t), ctypes.c_int, ctypes.c_char_p],
    ),
    (
        "kith_control_response_header",
        ctypes.c_int,
        [ctypes.POINTER(kith_control_response_t), ctypes.c_char_p, ctypes.c_char_p],
    ),
    (
        "kith_control_response_body",
        ctypes.c_int,
        [ctypes.POINTER(kith_control_response_t), ctypes.c_void_p, ctypes.c_uint32],
    ),
    (
        "kith_control_reject_overflow",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_control_t),
            ctypes.POINTER(kith_control_response_t),
            ctypes.c_char_p,
            ctypes.c_uint32,
        ],
    ),
]


def configure(lib: ctypes.CDLL) -> None:
    """Attach argtypes/restype to every KITH_API symbol on `lib`."""
    for name, restype, argtypes in _FUNCTIONS:
        fn = getattr(lib, name)
        fn.restype = restype
        fn.argtypes = argtypes
