# Auto-generated by tools/gen_ctypes.py from:
#   kith/coord/coord.h
# Regenerate via `python3 tools/gen_ctypes.py`. Do not edit by hand.


from __future__ import annotations

import ctypes
from enum import IntEnum

from kith._generated.fabric import kith_fabric_cell_key_t
from kith._generated.types import kith_allocator_t


class kith_coord(ctypes.Structure):
    pass


kith_coord_t = kith_coord


class kith_coord_bus(ctypes.Structure):
    pass


kith_coord_bus_t = kith_coord_bus


class kith_coord_params(ctypes.Structure):
    pass


kith_coord_params_t = kith_coord_params


class kith_coord_bus_params(ctypes.Structure):
    pass


kith_coord_bus_params_t = kith_coord_bus_params


class kith_coord_authority(ctypes.Structure):
    pass


kith_coord_authority_t = kith_coord_authority


class kith_coord_cell_entry(ctypes.Structure):
    pass


kith_coord_cell_entry_t = kith_coord_cell_entry


class kith_coord_rebalance_contract(ctypes.Structure):
    pass


kith_coord_rebalance_contract_t = kith_coord_rebalance_contract


class kith_coord_bus_event(ctypes.Structure):
    pass


kith_coord_bus_event_t = kith_coord_bus_event


class kith_coord_bus_member_status(ctypes.Structure):
    pass


kith_coord_bus_member_status_t = kith_coord_bus_member_status


class kith_coord_format(IntEnum):
    KITH_COORD_CELL_SHARDS = 16


class kith_coord_default(IntEnum):
    KITH_COORD_DEFAULT_CELL_BUCKETS = 4096
    KITH_COORD_DEFAULT_DENSITY_STRIDE = 64
    KITH_COORD_DEFAULT_SPLIT_THRESHOLD = 200
    KITH_COORD_DEFAULT_MERGE_THRESHOLD = 50
    KITH_COORD_DEFAULT_SPLIT_DWELL_MS = 5000
    KITH_COORD_DEFAULT_MERGE_DWELL_MS = 10000


class kith_coord_bus_transport(IntEnum):
    KITH_COORD_BUS_TRANSPORT_LOOPBACK = 0


kith_coord_bus_transport_t = kith_coord_bus_transport


class kith_coord_bus_event_type(IntEnum):
    KITH_COORD_BUS_EVENT_REBALANCE = 0
    KITH_COORD_BUS_EVENT_MEMBERSHIP = 1
    KITH_COORD_BUS_EVENT_SNAPSHOT_REQUEST = 2


kith_coord_bus_event_type_t = kith_coord_bus_event_type

kith_coord_params._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("instance_id", ctypes.c_uint32),
    ("cell_bucket_count", ctypes.c_uint32),
    ("density_stride", ctypes.c_uint32),
    ("split_threshold", ctypes.c_uint32),
    ("merge_threshold", ctypes.c_uint32),
    ("split_min_dwell_ms", ctypes.c_uint64),
    ("merge_min_dwell_ms", ctypes.c_uint64),
    ("pad", ctypes.c_uint32),
    ("reserved", ctypes.c_void_p * 8),
]

kith_coord_bus_params._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("instance_id", ctypes.c_uint32),
    ("transport", ctypes.c_uint32),
    ("pad", ctypes.c_uint32),
    ("reserved", ctypes.c_void_p * 8),
]

kith_coord_authority._fields_ = [
    ("instance_id", ctypes.c_uint32),
    ("authority_epoch", ctypes.c_uint32),
]

kith_coord_cell_entry._fields_ = [
    ("key", kith_fabric_cell_key_t),
    ("instance_id", ctypes.c_uint32),
    ("authority_epoch", ctypes.c_uint32),
]

kith_coord_rebalance_contract._fields_ = [
    ("key", kith_fabric_cell_key_t),
    ("source_instance_id", ctypes.c_uint32),
    ("target_instance_id", ctypes.c_uint32),
    ("authority_epoch", ctypes.c_uint32),
    ("pad", ctypes.c_uint32),
]

kith_coord_bus_event._fields_ = [
    ("event_type", ctypes.c_uint32),
    ("zone", ctypes.c_uint32),
    ("source_instance_id", ctypes.c_uint32),
    ("payload_len", ctypes.c_uint32),
    ("timestamp_ms", ctypes.c_uint64),
    ("payload", ctypes.c_void_p),
]

kith_coord_bus_member_status._fields_ = [
    ("instance_id", ctypes.c_uint32),
    ("heartbeat_ms", ctypes.c_uint64),
    ("owned_cell_count", ctypes.c_uint32),
    ("active_input_count", ctypes.c_uint32),
]

# ---------------------------------------------------------------------------
# function signatures
# ---------------------------------------------------------------------------
_FUNCTIONS: list[tuple[str, object, list[object]]] = [
    (
        "kith_coord_create",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_coord_params_t),
            ctypes.POINTER(kith_coord_bus_t),
            ctypes.POINTER(kith_allocator_t),
            ctypes.POINTER(ctypes.POINTER(kith_coord_t)),
        ],
    ),
    ("kith_coord_destroy", None, [ctypes.POINTER(kith_coord_t)]),
    (
        "kith_coord_authority",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_coord_t),
            ctypes.POINTER(kith_fabric_cell_key_t),
            ctypes.POINTER(kith_coord_authority_t),
        ],
    ),
    (
        "kith_coord_set_authority",
        ctypes.c_int,
        [ctypes.POINTER(kith_coord_t), ctypes.POINTER(kith_fabric_cell_key_t), ctypes.c_uint32],
    ),
    (
        "kith_coord_clear_authority",
        ctypes.c_int,
        [ctypes.POINTER(kith_coord_t), ctypes.POINTER(kith_fabric_cell_key_t)],
    ),
    ("kith_coord_cell_count", ctypes.c_uint32, [ctypes.POINTER(kith_coord_t)]),
    (
        "kith_coord_owned_cell_count",
        ctypes.c_uint32,
        [ctypes.POINTER(kith_coord_t), ctypes.c_uint32],
    ),
    (
        "kith_coord_snapshot_zone",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_coord_t),
            ctypes.c_uint32,
            ctypes.c_uint8,
            ctypes.POINTER(kith_coord_cell_entry_t),
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_size_t),
        ],
    ),
    (
        "kith_coord_report_density",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_coord_t),
            ctypes.POINTER(kith_fabric_cell_key_t),
            ctypes.c_uint32,
            ctypes.c_uint64,
        ],
    ),
    ("kith_coord_tick", ctypes.c_int, [ctypes.POINTER(kith_coord_t), ctypes.c_uint64]),
    (
        "kith_coord_on_rebalance",
        ctypes.c_int,
        [ctypes.POINTER(kith_coord_t), ctypes.POINTER(kith_coord_rebalance_contract_t)],
    ),
    (
        "kith_coord_bus_create",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_coord_bus_params_t),
            ctypes.POINTER(kith_allocator_t),
            ctypes.POINTER(ctypes.POINTER(kith_coord_bus_t)),
        ],
    ),
    ("kith_coord_bus_destroy", None, [ctypes.POINTER(kith_coord_bus_t)]),
    ("kith_coord_bus_instance_id", ctypes.c_uint32, [ctypes.POINTER(kith_coord_bus_t)]),
    ("kith_coord_bus_member_count", ctypes.c_uint32, [ctypes.POINTER(kith_coord_bus_t)]),
    (
        "kith_coord_bus_member_status",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_coord_bus_t),
            ctypes.c_uint32,
            ctypes.POINTER(kith_coord_bus_member_status_t),
        ],
    ),
    (
        "kith_coord_bus_add_member",
        ctypes.c_int,
        [ctypes.POINTER(kith_coord_bus_t), ctypes.c_uint32],
    ),
    ("kith_coord_bus_tick", ctypes.c_int, [ctypes.POINTER(kith_coord_bus_t), ctypes.c_uint64]),
    ("kith_coord_bus_subscribe", ctypes.c_int, [ctypes.POINTER(kith_coord_bus_t), ctypes.c_uint32]),
    (
        "kith_coord_bus_unsubscribe",
        ctypes.c_int,
        [ctypes.POINTER(kith_coord_bus_t), ctypes.c_uint32],
    ),
    (
        "kith_coord_bus_publish",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_coord_bus_t),
            ctypes.c_uint32,
            ctypes.c_uint32,
            ctypes.c_void_p,
            ctypes.c_uint32,
        ],
    ),
    (
        "kith_coord_bus_drain",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_coord_bus_t),
            ctypes.POINTER(kith_coord_bus_event_t),
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_size_t),
        ],
    ),
]


def configure(lib: ctypes.CDLL) -> None:
    """Attach argtypes/restype to every KITH_API symbol on `lib`."""
    for name, restype, argtypes in _FUNCTIONS:
        fn = getattr(lib, name)
        fn.restype = restype
        fn.argtypes = argtypes
