# Auto-generated by tools/gen_ctypes.py from:
#   kith/db/db.h
# Regenerate via `python3 tools/gen_ctypes.py`. Do not edit by hand.


from __future__ import annotations

import ctypes
from enum import IntEnum

from kith._generated.reactor import kith_reactor_t
from kith._generated.types import kith_allocator_t


class kith_db(ctypes.Structure):
    pass


kith_db_t = kith_db


class kith_db_params(ctypes.Structure):
    pass


kith_db_params_t = kith_db_params


class kith_db_reply(ctypes.Structure):
    pass


kith_db_reply_t = kith_db_reply


class kith_db_session(ctypes.Structure):
    pass


kith_db_session_t = kith_db_session


class kith_db_default(IntEnum):
    KITH_DB_DEFAULT_PORT = 5432
    KITH_DB_DEFAULT_MIN_CONNECTIONS = 1
    KITH_DB_DEFAULT_MAX_CONNECTIONS = 4
    KITH_DB_DEFAULT_TIMEOUT_MS = 5000


kith_db_reply_fn = ctypes.CFUNCTYPE(None, ctypes.POINTER(kith_db_reply))

kith_db_session_open_fn = ctypes.CFUNCTYPE(
    None, ctypes.POINTER(kith_db_session), ctypes.c_int, ctypes.c_void_p
)

kith_db_session_close_fn = ctypes.CFUNCTYPE(None, ctypes.c_int, ctypes.c_void_p)

kith_db_params._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("host", ctypes.c_char_p),
    ("port", ctypes.c_uint16),
    ("db_name", ctypes.c_char_p),
    ("user", ctypes.c_char_p),
    ("password", ctypes.c_char_p),
    ("min_connections", ctypes.c_uint32),
    ("max_connections", ctypes.c_uint32),
    ("connect_timeout_ms", ctypes.c_uint32),
    ("reserved", ctypes.c_void_p * 8),
]

# ---------------------------------------------------------------------------
# function signatures
# ---------------------------------------------------------------------------
_FUNCTIONS: list[tuple[str, object, list[object]]] = [
    (
        "kith_db_create",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_db_params_t),
            ctypes.POINTER(kith_reactor_t),
            ctypes.POINTER(kith_allocator_t),
            ctypes.POINTER(ctypes.POINTER(kith_db_t)),
        ],
    ),
    ("kith_db_destroy", None, [ctypes.POINTER(kith_db_t)]),
    (
        "kith_db_register_query",
        ctypes.c_int,
        [ctypes.POINTER(kith_db_t), ctypes.c_char_p, ctypes.c_char_p, ctypes.c_uint32],
    ),
    (
        "kith_db_lookup_query",
        ctypes.c_int,
        [ctypes.POINTER(kith_db_t), ctypes.c_char_p, ctypes.POINTER(ctypes.c_uint32)],
    ),
    (
        "kith_db_exec",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_db_t),
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_char_p),
            ctypes.c_uint32,
            kith_db_reply_fn,
            ctypes.c_void_p,
        ],
    ),
    (
        "kith_db_exec_sql",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_db_t),
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_char_p),
            ctypes.c_uint32,
            kith_db_reply_fn,
            ctypes.c_void_p,
        ],
    ),
    (
        "kith_db_session_open",
        ctypes.c_int,
        [ctypes.POINTER(kith_db_t), kith_db_session_open_fn, ctypes.c_void_p],
    ),
    (
        "kith_db_session_exec",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_db_session_t),
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_char_p),
            ctypes.c_uint32,
            kith_db_reply_fn,
            ctypes.c_void_p,
        ],
    ),
    (
        "kith_db_session_close",
        ctypes.c_int,
        [ctypes.POINTER(kith_db_session_t), kith_db_session_close_fn, ctypes.c_void_p],
    ),
    (
        "kith_db_reply_value",
        ctypes.c_char_p,
        [
            ctypes.POINTER(kith_db_reply_t),
            ctypes.c_uint32,
            ctypes.c_uint32,
            ctypes.POINTER(ctypes.c_size_t),
        ],
    ),
    (
        "kith_db_reply_is_null",
        ctypes.c_bool,
        [ctypes.POINTER(kith_db_reply_t), ctypes.c_uint32, ctypes.c_uint32],
    ),
    ("kith_db_reply_status", ctypes.c_int, [ctypes.POINTER(kith_db_reply_t)]),
    ("kith_db_reply_err_str", ctypes.c_char_p, [ctypes.POINTER(kith_db_reply_t)]),
    ("kith_db_reply_n_rows", ctypes.c_uint32, [ctypes.POINTER(kith_db_reply_t)]),
    ("kith_db_reply_n_cols", ctypes.c_uint32, [ctypes.POINTER(kith_db_reply_t)]),
    ("kith_db_reply_user_data", ctypes.c_void_p, [ctypes.POINTER(kith_db_reply_t)]),
]


def configure(lib: ctypes.CDLL) -> None:
    """Attach argtypes/restype to every KITH_API symbol on `lib`."""
    for name, restype, argtypes in _FUNCTIONS:
        fn = getattr(lib, name)
        fn.restype = restype
        fn.argtypes = argtypes
