# Auto-generated by tools/gen_ctypes.py from:
#   kith/fabric/fabric.h
# Regenerate via `python3 tools/gen_ctypes.py`. Do not edit by hand.


from __future__ import annotations

import ctypes
from enum import IntEnum

from kith._generated.sim import kith_sim_t
from kith._generated.types import kith_allocator_t


class kith_fabric(ctypes.Structure):
    pass


kith_fabric_t = kith_fabric


class kith_fabric_subscription(ctypes.Structure):
    pass


kith_fabric_subscription_t = kith_fabric_subscription


class kith_fabric_params(ctypes.Structure):
    pass


kith_fabric_params_t = kith_fabric_params


class kith_fabric_cell_key(ctypes.Structure):
    pass


kith_fabric_cell_key_t = kith_fabric_cell_key


class kith_fabric_cell_product(ctypes.Structure):
    pass


kith_fabric_cell_product_t = kith_fabric_cell_product


class kith_fabric_artifact(ctypes.Structure):
    pass


kith_fabric_artifact_t = kith_fabric_artifact


class kith_fabric_format(IntEnum):
    KITH_FABRIC_CELL_SHARDS = 16


class kith_fabric_default(IntEnum):
    KITH_FABRIC_DEFAULT_BUCKET_COUNT = 4096


class kith_fabric_product_level(IntEnum):
    KITH_FABRIC_LEVEL_FULL = 0
    KITH_FABRIC_LEVEL_REDUCED = 1
    KITH_FABRIC_LEVEL_CROWD = 2


kith_fabric_product_level_t = kith_fabric_product_level

kith_fabric_params._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("cell_bucket_count", ctypes.c_uint32),
    ("reserved", ctypes.c_void_p * 8),
]

kith_fabric_cell_key._fields_ = [
    ("zone", ctypes.c_uint32),
    ("cell_x", ctypes.c_int32),
    ("cell_y", ctypes.c_int32),
    ("cell_z", ctypes.c_int32),
    ("lod", ctypes.c_uint8),
    ("pad", ctypes.c_uint8 * 3),
]

kith_fabric_cell_product._fields_ = [
    ("key", kith_fabric_cell_key_t),
    ("authority_epoch", ctypes.c_uint32),
    ("publish_seq", ctypes.c_uint64),
    ("product_level", ctypes.c_uint32),
    ("actor_count", ctypes.c_uint32),
]

kith_fabric_artifact._fields_ = [
    ("actor_id", ctypes.c_uint64),
    ("pos_x", ctypes.c_int64),
    ("pos_y", ctypes.c_int64),
    ("pos_z", ctypes.c_int64),
    ("vel_x", ctypes.c_int64),
    ("vel_y", ctypes.c_int64),
    ("vel_z", ctypes.c_int64),
    ("input_tick", ctypes.c_uint32),
    ("update_seq", ctypes.c_uint32),
    ("product_level", ctypes.c_uint32),
]

# ---------------------------------------------------------------------------
# function signatures
# ---------------------------------------------------------------------------
_FUNCTIONS: list[tuple[str, object, list[object]]] = [
    (
        "kith_fabric_create",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_fabric_params_t),
            ctypes.POINTER(kith_sim_t),
            ctypes.POINTER(kith_allocator_t),
            ctypes.POINTER(ctypes.POINTER(kith_fabric_t)),
        ],
    ),
    ("kith_fabric_destroy", None, [ctypes.POINTER(kith_fabric_t)]),
    (
        "kith_fabric_publish",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_fabric_t),
            ctypes.POINTER(kith_fabric_cell_key_t),
            ctypes.c_uint32,
            ctypes.POINTER(ctypes.c_uint64),
        ],
    ),
    (
        "kith_fabric_remove_cell",
        ctypes.c_int,
        [ctypes.POINTER(kith_fabric_t), ctypes.POINTER(kith_fabric_cell_key_t)],
    ),
    ("kith_fabric_remove_zone", ctypes.c_int, [ctypes.POINTER(kith_fabric_t), ctypes.c_uint32]),
    (
        "kith_fabric_snapshot_cell",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_fabric_t),
            ctypes.POINTER(kith_fabric_cell_key_t),
            ctypes.c_uint32,
            ctypes.POINTER(kith_fabric_artifact_t),
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_size_t),
        ],
    ),
    (
        "kith_fabric_snapshot_zone_cells",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_fabric_t),
            ctypes.c_uint32,
            ctypes.c_uint8,
            ctypes.POINTER(kith_fabric_cell_product_t),
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_size_t),
        ],
    ),
    (
        "kith_fabric_cell_product",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_fabric_t),
            ctypes.POINTER(kith_fabric_cell_key_t),
            ctypes.POINTER(kith_fabric_cell_product_t),
        ],
    ),
    ("kith_fabric_product_count", ctypes.c_uint64, [ctypes.POINTER(kith_fabric_t)]),
    ("kith_fabric_publish_total", ctypes.c_uint64, [ctypes.POINTER(kith_fabric_t)]),
    (
        "kith_fabric_create_subscription",
        ctypes.c_int,
        [ctypes.POINTER(kith_fabric_t), ctypes.POINTER(ctypes.POINTER(kith_fabric_subscription_t))],
    ),
    ("kith_fabric_subscription_destroy", None, [ctypes.POINTER(kith_fabric_subscription_t)]),
    (
        "kith_fabric_subscription_add",
        ctypes.c_int,
        [ctypes.POINTER(kith_fabric_subscription_t), ctypes.POINTER(kith_fabric_cell_key_t)],
    ),
    (
        "kith_fabric_subscription_remove",
        ctypes.c_int,
        [ctypes.POINTER(kith_fabric_subscription_t), ctypes.POINTER(kith_fabric_cell_key_t)],
    ),
    (
        "kith_fabric_subscription_size",
        ctypes.c_size_t,
        [ctypes.POINTER(kith_fabric_subscription_t)],
    ),
    (
        "kith_fabric_drain",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_fabric_t),
            ctypes.POINTER(kith_fabric_subscription_t),
            ctypes.POINTER(kith_fabric_cell_product_t),
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_size_t),
        ],
    ),
]


def configure(lib: ctypes.CDLL) -> None:
    """Attach argtypes/restype to every KITH_API symbol on `lib`."""
    for name, restype, argtypes in _FUNCTIONS:
        fn = getattr(lib, name)
        fn.restype = restype
        fn.argtypes = argtypes
