# Auto-generated by tools/gen_ctypes.py from:
#   kith/logger/logger.h
# Regenerate via `python3 tools/gen_ctypes.py`. Do not edit by hand.


from __future__ import annotations

import ctypes
from enum import IntEnum

from kith._generated.types import kith_allocator_t


class kith_logger_field(ctypes.Structure):
    pass


kith_logger_field_t = kith_logger_field


class kith_logger(ctypes.Structure):
    pass


kith_logger_t = kith_logger


class kith_logger_params(ctypes.Structure):
    pass


kith_logger_params_t = kith_logger_params


class kith_logger_level(IntEnum):
    KITH_LOG_LEVEL_TRACE = 0
    KITH_LOG_LEVEL_DEBUG = 1
    KITH_LOG_LEVEL_INFO = 2
    KITH_LOG_LEVEL_WARN = 3
    KITH_LOG_LEVEL_ERROR = 4


kith_logger_level_t = kith_logger_level

kith_logger_field._fields_ = [
    ("key", ctypes.c_char_p),
    ("value", ctypes.c_char_p),
]

kith_logger_params._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("name", ctypes.c_char_p),
    ("file_path", ctypes.c_char_p),
    ("jsonl_path", ctypes.c_char_p),
    ("stdout_enabled", ctypes.c_bool),
    ("min_level", ctypes.c_uint32),
    ("reserved", ctypes.c_void_p * 8),
]

# ---------------------------------------------------------------------------
# function signatures
# ---------------------------------------------------------------------------
_FUNCTIONS: list[tuple[str, object, list[object]]] = [
    (
        "kith_logger_create",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_logger_params_t),
            ctypes.POINTER(kith_allocator_t),
            ctypes.POINTER(ctypes.POINTER(kith_logger_t)),
        ],
    ),
    ("kith_logger_destroy", None, [ctypes.POINTER(kith_logger_t)]),
    ("kith_logger_enabled", ctypes.c_bool, [ctypes.POINTER(kith_logger_t), ctypes.c_uint32]),
    (
        "kith_logger_log",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_logger_t),
            ctypes.c_uint32,
            ctypes.c_char_p,
            ctypes.c_uint,
            ctypes.POINTER(kith_logger_field_t),
            ctypes.c_size_t,
            ctypes.c_char_p,
        ],
    ),
    ("kith_logger_set_level", ctypes.c_int, [ctypes.POINTER(kith_logger_t), ctypes.c_uint32]),
    ("kith_logger_level", ctypes.c_uint32, [ctypes.POINTER(kith_logger_t)]),
]


def configure(lib: ctypes.CDLL) -> None:
    """Attach argtypes/restype to every KITH_API symbol on `lib`."""
    for name, restype, argtypes in _FUNCTIONS:
        fn = getattr(lib, name)
        fn.restype = restype
        fn.argtypes = argtypes
