# Auto-generated by tools/gen_ctypes.py from:
#   kith/metrics/metrics.h
# Regenerate via `python3 tools/gen_ctypes.py`. Do not edit by hand.


from __future__ import annotations

import ctypes
from enum import IntEnum

from kith._generated.types import kith_allocator_t


class kith_metrics_label(ctypes.Structure):
    pass


kith_metrics_label_t = kith_metrics_label


class kith_metrics(ctypes.Structure):
    pass


kith_metrics_t = kith_metrics


class kith_metrics_params(ctypes.Structure):
    pass


kith_metrics_params_t = kith_metrics_params


class kith_metrics_kind(IntEnum):
    KITH_METRICS_KIND_COUNTER = 0
    KITH_METRICS_KIND_GAUGE = 1
    KITH_METRICS_KIND_HISTOGRAM = 2


kith_metrics_kind_t = kith_metrics_kind

kith_metrics_label._fields_ = [
    ("key", ctypes.c_char_p),
    ("value", ctypes.c_char_p),
]

kith_metrics_params._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("prefix", ctypes.c_char_p),
    ("reserved", ctypes.c_void_p * 8),
]

# ---------------------------------------------------------------------------
# function signatures
# ---------------------------------------------------------------------------
_FUNCTIONS: list[tuple[str, object, list[object]]] = [
    (
        "kith_metrics_create",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_metrics_params_t),
            ctypes.POINTER(kith_allocator_t),
            ctypes.POINTER(ctypes.POINTER(kith_metrics_t)),
        ],
    ),
    ("kith_metrics_destroy", None, [ctypes.POINTER(kith_metrics_t)]),
    (
        "kith_metrics_counter_add",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_metrics_t),
            ctypes.c_char_p,
            ctypes.POINTER(kith_metrics_label_t),
            ctypes.c_size_t,
            ctypes.c_uint64,
        ],
    ),
    (
        "kith_metrics_gauge_set",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_metrics_t),
            ctypes.c_char_p,
            ctypes.POINTER(kith_metrics_label_t),
            ctypes.c_size_t,
            ctypes.c_int64,
        ],
    ),
    (
        "kith_metrics_histogram_observe",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_metrics_t),
            ctypes.c_char_p,
            ctypes.POINTER(kith_metrics_label_t),
            ctypes.c_size_t,
            ctypes.c_uint64,
        ],
    ),
    (
        "kith_metrics_render_prometheus",
        ctypes.c_size_t,
        [ctypes.POINTER(kith_metrics_t), ctypes.c_char_p, ctypes.c_size_t],
    ),
    (
        "kith_metrics_export_otlp",
        ctypes.c_size_t,
        [ctypes.POINTER(kith_metrics_t), ctypes.c_char_p, ctypes.c_size_t],
    ),
]


def configure(lib: ctypes.CDLL) -> None:
    """Attach argtypes/restype to every KITH_API symbol on `lib`."""
    for name, restype, argtypes in _FUNCTIONS:
        fn = getattr(lib, name)
        fn.restype = restype
        fn.argtypes = argtypes
