# Auto-generated by tools/gen_ctypes.py from:
#   kith/net/net.h
# Regenerate via `python3 tools/gen_ctypes.py`. Do not edit by hand.


from __future__ import annotations

import ctypes
from enum import IntEnum

from kith._generated.proto import kith_proto_frame, kith_proto_t
from kith._generated.types import kith_allocator_t


class kith_net(ctypes.Structure):
    pass


kith_net_t = kith_net


class kith_net_conn(ctypes.Structure):
    pass


kith_net_conn_t = kith_net_conn


class kith_net_frame(ctypes.Structure):
    pass


kith_net_frame_t = kith_net_frame


class kith_net_params(ctypes.Structure):
    pass


kith_net_params_t = kith_net_params


class kith_net_default(IntEnum):
    KITH_NET_DEFAULT_MAX_CONNECTIONS = 4096
    KITH_NET_DEFAULT_READ_BUF_INITIAL = 4096
    KITH_NET_DEFAULT_READ_BUF_MAX = 262144
    KITH_NET_MIN_READ_BUF_MAX = 8192
    KITH_NET_DEFAULT_IN_HIGH_WATER = 196608
    KITH_NET_DEFAULT_IN_LOW_WATER = 98304
    KITH_NET_DEFAULT_OUT_HIGH_WATER = 262144
    KITH_NET_DEFAULT_OUT_LOW_WATER = 131072
    KITH_NET_DEFAULT_OUT_DRAIN_CAP = 65536


class kith_net_event(IntEnum):
    KITH_NET_IN = 1
    KITH_NET_OUT = 2


kith_net_message_fn = ctypes.CFUNCTYPE(
    None, ctypes.POINTER(kith_net_conn), ctypes.POINTER(kith_proto_frame), ctypes.c_void_p
)

kith_net_params._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("max_connections", ctypes.c_uint32),
    ("listen_backlog", ctypes.c_uint32),
    ("read_buffer_initial", ctypes.c_uint32),
    ("read_buffer_max", ctypes.c_uint32),
    ("in_high_water", ctypes.c_uint32),
    ("in_low_water", ctypes.c_uint32),
    ("out_high_water", ctypes.c_uint32),
    ("out_low_water", ctypes.c_uint32),
    ("out_drain_cap", ctypes.c_uint32),
    ("reserved", ctypes.c_void_p * 8),
]

# ---------------------------------------------------------------------------
# function signatures
# ---------------------------------------------------------------------------
_FUNCTIONS: list[tuple[str, object, list[object]]] = [
    (
        "kith_net_create",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_net_params_t),
            ctypes.POINTER(kith_proto_t),
            ctypes.POINTER(kith_allocator_t),
            ctypes.POINTER(ctypes.POINTER(kith_net_t)),
        ],
    ),
    ("kith_net_destroy", None, [ctypes.POINTER(kith_net_t)]),
    (
        "kith_net_listen",
        ctypes.c_int,
        [ctypes.POINTER(kith_net_t), ctypes.c_char_p, ctypes.c_uint16],
    ),
    ("kith_net_listener_fd", ctypes.c_int, [ctypes.POINTER(kith_net_t)]),
    (
        "kith_net_accept",
        ctypes.c_int,
        [ctypes.POINTER(kith_net_t), ctypes.POINTER(ctypes.POINTER(kith_net_conn_t))],
    ),
    ("kith_net_conn_fd", ctypes.c_int, [ctypes.POINTER(kith_net_conn_t)]),
    ("kith_net_conn_acquire", None, [ctypes.POINTER(kith_net_conn_t)]),
    ("kith_net_conn_release", None, [ctypes.POINTER(kith_net_conn_t)]),
    ("kith_net_conn_close", None, [ctypes.POINTER(kith_net_conn_t)]),
    (
        "kith_net_conn_read",
        ctypes.c_int,
        [ctypes.POINTER(kith_net_conn_t), kith_net_message_fn, ctypes.c_void_p],
    ),
    (
        "kith_net_frame_create",
        ctypes.POINTER(kith_net_frame_t),
        [ctypes.POINTER(kith_net_t), ctypes.c_uint32],
    ),
    ("kith_net_frame_data", ctypes.c_void_p, [ctypes.POINTER(kith_net_frame_t)]),
    ("kith_net_frame_len", ctypes.c_uint32, [ctypes.POINTER(kith_net_frame_t)]),
    ("kith_net_frame_set_len", None, [ctypes.POINTER(kith_net_frame_t), ctypes.c_uint32]),
    ("kith_net_frame_acquire", None, [ctypes.POINTER(kith_net_frame_t)]),
    ("kith_net_frame_release", None, [ctypes.POINTER(kith_net_frame_t)]),
    (
        "kith_net_conn_enqueue",
        ctypes.c_int,
        [ctypes.POINTER(kith_net_conn_t), ctypes.POINTER(kith_net_frame_t)],
    ),
    ("kith_net_conn_write", ctypes.c_int, [ctypes.POINTER(kith_net_conn_t)]),
    (
        "kith_net_write_deferrals",
        ctypes.c_int,
        [ctypes.POINTER(kith_net_t), ctypes.POINTER(ctypes.c_uint64)],
    ),
    (
        "kith_net_rejections",
        ctypes.c_int,
        [ctypes.POINTER(kith_net_t), ctypes.POINTER(ctypes.c_uint64)],
    ),
    ("kith_net_conn_events", ctypes.c_uint, [ctypes.POINTER(kith_net_conn_t)]),
]


def configure(lib: ctypes.CDLL) -> None:
    """Attach argtypes/restype to every KITH_API symbol on `lib`."""
    for name, restype, argtypes in _FUNCTIONS:
        fn = getattr(lib, name)
        fn.restype = restype
        fn.argtypes = argtypes
