# Auto-generated by tools/gen_ctypes.py from:
#   kith/proto/proto.h
# Regenerate via `python3 tools/gen_ctypes.py`. Do not edit by hand.


from __future__ import annotations

import ctypes
from enum import IntEnum

from kith._generated.types import kith_allocator_t


class kith_proto(ctypes.Structure):
    pass


kith_proto_t = kith_proto


class kith_proto_params(ctypes.Structure):
    pass


kith_proto_params_t = kith_proto_params


class kith_proto_frame(ctypes.Structure):
    pass


kith_proto_frame_t = kith_proto_frame


class kith_proto_format(IntEnum):
    KITH_PROTO_MAGIC0 = 75
    KITH_PROTO_MAGIC1 = 84
    KITH_PROTO_VERSION = 1
    KITH_PROTO_HDR_SIZE = 10
    KITH_PROTO_CORR_TRAILER_SIZE = 8
    KITH_PROTO_TYPE_USER_BASE = 1000


class kith_proto_flag(IntEnum):
    KITH_PROTO_FLAG_CORRELATION = 2


kith_proto_flag_t = kith_proto_flag

kith_proto_params._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("max_payload", ctypes.c_uint32),
    ("reserved", ctypes.c_void_p * 8),
]

kith_proto_frame._fields_ = [
    ("type_id", ctypes.c_uint16),
    ("flags", ctypes.c_uint8),
    ("has_correlation", ctypes.c_bool),
    ("correlation_id", ctypes.c_uint64),
    ("payload", ctypes.c_void_p),
    ("payload_len", ctypes.c_uint32),
]

# ---------------------------------------------------------------------------
# macro constants
# ---------------------------------------------------------------------------
KITH_PROTO_DEFAULT_MAX_PAYLOAD = 1048576

# ---------------------------------------------------------------------------
# function signatures
# ---------------------------------------------------------------------------
_FUNCTIONS: list[tuple[str, object, list[object]]] = [
    (
        "kith_proto_create",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_proto_params_t),
            ctypes.POINTER(kith_allocator_t),
            ctypes.POINTER(ctypes.POINTER(kith_proto_t)),
        ],
    ),
    ("kith_proto_destroy", None, [ctypes.POINTER(kith_proto_t)]),
    (
        "kith_proto_register_type_id",
        ctypes.c_int,
        [ctypes.POINTER(kith_proto_t), ctypes.c_char_p, ctypes.c_uint16],
    ),
    (
        "kith_proto_lookup_type",
        ctypes.c_int,
        [ctypes.POINTER(kith_proto_t), ctypes.c_char_p, ctypes.POINTER(ctypes.c_uint16)],
    ),
    ("kith_proto_type_name", ctypes.c_char_p, [ctypes.POINTER(kith_proto_t), ctypes.c_uint16]),
    (
        "kith_proto_encode",
        ctypes.c_size_t,
        [
            ctypes.POINTER(kith_proto_t),
            ctypes.c_uint16,
            ctypes.c_uint8,
            ctypes.c_uint64,
            ctypes.c_void_p,
            ctypes.c_uint32,
            ctypes.c_void_p,
            ctypes.c_size_t,
        ],
    ),
    (
        "kith_proto_decode",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_proto_t),
            ctypes.c_void_p,
            ctypes.c_size_t,
            ctypes.POINTER(kith_proto_frame_t),
            ctypes.POINTER(ctypes.c_size_t),
        ],
    ),
    (
        "kith_proto_declared_total",
        ctypes.c_int,
        [ctypes.c_void_p, ctypes.c_size_t, ctypes.POINTER(ctypes.c_size_t)],
    ),
    (
        "kith_proto_rejections",
        ctypes.c_int,
        [ctypes.POINTER(kith_proto_t), ctypes.POINTER(ctypes.c_uint64)],
    ),
    ("kith_proto_correlation_hex", ctypes.c_size_t, [ctypes.c_uint64, ctypes.c_char_p]),
]


def configure(lib: ctypes.CDLL) -> None:
    """Attach argtypes/restype to every KITH_API symbol on `lib`."""
    for name, restype, argtypes in _FUNCTIONS:
        fn = getattr(lib, name)
        fn.restype = restype
        fn.argtypes = argtypes
