# Auto-generated by tools/gen_ctypes.py from:
#   kith/reactor/reactor.h
# Regenerate via `python3 tools/gen_ctypes.py`. Do not edit by hand.


from __future__ import annotations

import ctypes
from enum import IntEnum

from kith._generated.types import kith_allocator_t


class kith_reactor(ctypes.Structure):
    pass


kith_reactor_t = kith_reactor


class kith_reactor_params(ctypes.Structure):
    pass


kith_reactor_params_t = kith_reactor_params


class kith_reactor_default(IntEnum):
    KITH_REACTOR_DEFAULT_MAX_FDS = 2048
    KITH_REACTOR_DEFAULT_TASK_CAPACITY = 1024


class kith_reactor_event(IntEnum):
    KITH_REACTOR_IN = 1
    KITH_REACTOR_OUT = 2
    KITH_REACTOR_HUP = 8
    KITH_REACTOR_ERR = 16


kith_reactor_cb = ctypes.CFUNCTYPE(None, ctypes.c_int, ctypes.c_uint, ctypes.c_void_p)

kith_reactor_task_cb = ctypes.CFUNCTYPE(None, ctypes.c_void_p)

kith_reactor_params._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("max_fds", ctypes.c_uint32),
    ("task_capacity", ctypes.c_uint32),
    ("reserved", ctypes.c_void_p * 8),
]

# ---------------------------------------------------------------------------
# function signatures
# ---------------------------------------------------------------------------
_FUNCTIONS: list[tuple[str, object, list[object]]] = [
    (
        "kith_reactor_create",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_reactor_params_t),
            ctypes.POINTER(kith_allocator_t),
            ctypes.POINTER(ctypes.POINTER(kith_reactor_t)),
        ],
    ),
    ("kith_reactor_destroy", None, [ctypes.POINTER(kith_reactor_t)]),
    (
        "kith_reactor_add",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_reactor_t),
            ctypes.c_int,
            ctypes.c_uint,
            kith_reactor_cb,
            ctypes.c_void_p,
        ],
    ),
    (
        "kith_reactor_mod",
        ctypes.c_int,
        [ctypes.POINTER(kith_reactor_t), ctypes.c_int, ctypes.c_uint],
    ),
    ("kith_reactor_del", ctypes.c_int, [ctypes.POINTER(kith_reactor_t), ctypes.c_int]),
    (
        "kith_reactor_submit",
        ctypes.c_int,
        [ctypes.POINTER(kith_reactor_t), kith_reactor_task_cb, ctypes.c_void_p],
    ),
    (
        "kith_reactor_schedule",
        ctypes.c_int,
        [ctypes.POINTER(kith_reactor_t), ctypes.c_uint64, kith_reactor_task_cb, ctypes.c_void_p],
    ),
    ("kith_reactor_run", ctypes.c_int, [ctypes.POINTER(kith_reactor_t)]),
    ("kith_reactor_stop", None, [ctypes.POINTER(kith_reactor_t)]),
    ("kith_reactor_now_ms", ctypes.c_uint64, [ctypes.POINTER(kith_reactor_t)]),
    (
        "kith_reactor_ring_sizes",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_reactor_t),
            ctypes.POINTER(ctypes.c_uint),
            ctypes.POINTER(ctypes.c_uint),
        ],
    ),
]


def configure(lib: ctypes.CDLL) -> None:
    """Attach argtypes/restype to every KITH_API symbol on `lib`."""
    for name, restype, argtypes in _FUNCTIONS:
        fn = getattr(lib, name)
        fn.restype = restype
        fn.argtypes = argtypes
