# Auto-generated by tools/gen_ctypes.py from:
#   kith/server/server.h
# Regenerate via `python3 tools/gen_ctypes.py`. Do not edit by hand.


from __future__ import annotations

import ctypes
from enum import IntEnum

from kith._generated.config import kith_config_t
from kith._generated.control import kith_control_t
from kith._generated.db import kith_db_t
from kith._generated.fabric import kith_fabric_t
from kith._generated.gateway import kith_gateway_t
from kith._generated.proto import kith_proto_t
from kith._generated.sim import kith_sim_t
from kith._generated.types import kith_allocator_t


class kith_server(ctypes.Structure):
    pass


kith_server_t = kith_server


class kith_server_params(ctypes.Structure):
    pass


kith_server_params_t = kith_server_params


class kith_server_default(IntEnum):
    KITH_SERVER_DEFAULT_TICK_HZ = 20
    KITH_SERVER_DEFAULT_LISTEN_PORT = 7777
    KITH_SERVER_DEFAULT_PYTHON_WORKERS = 1


class kith_server_topology(IntEnum):
    KITH_SERVER_TOPOLOGY_DISTRIBUTED = 0
    KITH_SERVER_TOPOLOGY_EMBEDDED = 1


kith_server_topology_t = kith_server_topology


class kith_server_status(IntEnum):
    KITH_SERVER_STATUS_CREATED = 0
    KITH_SERVER_STATUS_RUNNING = 1
    KITH_SERVER_STATUS_DRAINING = 2
    KITH_SERVER_STATUS_STOPPED = 3


kith_server_status_t = kith_server_status


class kith_server_handler_flag(IntEnum):
    KITH_SERVER_HANDLER_NONE = 0
    KITH_SERVER_HANDLER_PYTHON = 1


kith_server_handler_flag_t = kith_server_handler_flag

kith_server_tick_fn = ctypes.CFUNCTYPE(None, ctypes.c_ulong, ctypes.c_void_p)

kith_server_poll_fn = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p)

kith_server_params._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("config", ctypes.POINTER(kith_config_t)),
    ("topology", ctypes.c_uint32),
    ("instance_id", ctypes.c_uint32),
    ("listen_host", ctypes.c_char_p),
    ("listen_port", ctypes.c_uint16),
    ("tick_hz", ctypes.c_uint16),
    ("python_worker_count", ctypes.c_uint32),
    ("handler_table_size", ctypes.c_uint32),
    ("replication_type_id", ctypes.c_uint16),
    ("replication_batch_type_id", ctypes.c_uint16),
    ("delivery_strategy", ctypes.c_char_p),
    ("delivery_config", ctypes.c_void_p),
    ("delivery_worker_count", ctypes.c_uint32),
    ("delivery_wait_budget_us", ctypes.c_uint32),
    ("self_echo_disabled", ctypes.c_bool),
    ("control_write_buffer_cap", ctypes.c_uint32),
    ("view_max_subjects", ctypes.c_uint32),
    ("view_refresh_interval_ms", ctypes.c_uint32),
    ("cache_refresh_interval_ms", ctypes.c_uint32),
    ("reserved", ctypes.c_void_p * 8),
]

# ---------------------------------------------------------------------------
# function signatures
# ---------------------------------------------------------------------------
_FUNCTIONS: list[tuple[str, object, list[object]]] = [
    (
        "kith_server_create",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_server_params_t),
            ctypes.POINTER(kith_allocator_t),
            ctypes.POINTER(ctypes.POINTER(kith_server_t)),
        ],
    ),
    ("kith_server_destroy", None, [ctypes.POINTER(kith_server_t)]),
    ("kith_server_run", ctypes.c_int, [ctypes.POINTER(kith_server_t)]),
    ("kith_server_shutdown", ctypes.c_int, [ctypes.POINTER(kith_server_t)]),
    ("kith_server_status", ctypes.c_uint32, [ctypes.POINTER(kith_server_t)]),
    ("kith_server_listen_port", ctypes.c_uint16, [ctypes.POINTER(kith_server_t)]),
    ("kith_server_control_port", ctypes.c_uint16, [ctypes.POINTER(kith_server_t)]),
    (
        "kith_server_register_tick_handler",
        ctypes.c_int,
        [ctypes.POINTER(kith_server_t), kith_server_tick_fn, ctypes.c_void_p, ctypes.c_uint32],
    ),
    ("kith_server_unregister_tick_handler", ctypes.c_int, [ctypes.POINTER(kith_server_t)]),
    (
        "kith_server_register_poll_observer",
        ctypes.c_int,
        [ctypes.POINTER(kith_server_t), kith_server_poll_fn, ctypes.c_void_p],
    ),
    (
        "kith_server_tick_drops",
        ctypes.c_int,
        [ctypes.POINTER(kith_server_t), ctypes.POINTER(ctypes.c_uint64)],
    ),
    ("kith_server_gateway", ctypes.POINTER(kith_gateway_t), [ctypes.POINTER(kith_server_t)]),
    ("kith_server_sim", ctypes.POINTER(kith_sim_t), [ctypes.POINTER(kith_server_t)]),
    ("kith_server_fabric", ctypes.POINTER(kith_fabric_t), [ctypes.POINTER(kith_server_t)]),
    ("kith_server_proto", ctypes.POINTER(kith_proto_t), [ctypes.POINTER(kith_server_t)]),
    ("kith_server_control", ctypes.POINTER(kith_control_t), [ctypes.POINTER(kith_server_t)]),
    ("kith_server_db", ctypes.POINTER(kith_db_t), [ctypes.POINTER(kith_server_t)]),
]


def configure(lib: ctypes.CDLL) -> None:
    """Attach argtypes/restype to every KITH_API symbol on `lib`."""
    for name, restype, argtypes in _FUNCTIONS:
        fn = getattr(lib, name)
        fn.restype = restype
        fn.argtypes = argtypes
