# Auto-generated by tools/gen_ctypes.py from:
#   kith/sim/sim.h
# Regenerate via `python3 tools/gen_ctypes.py`. Do not edit by hand.


from __future__ import annotations

import ctypes
from enum import IntEnum

from kith._generated.types import kith_allocator, kith_allocator_t


class kith_sim(ctypes.Structure):
    pass


kith_sim_t = kith_sim


class kith_sim_model(ctypes.Structure):
    pass


kith_sim_model_t = kith_sim_model


class kith_sim_config(ctypes.Structure):
    pass


kith_sim_config_t = kith_sim_config


class kith_sim_params(ctypes.Structure):
    pass


kith_sim_params_t = kith_sim_params


class kith_sim_actor(ctypes.Structure):
    pass


kith_sim_actor_t = kith_sim_actor


class kith_sim_input(ctypes.Structure):
    pass


kith_sim_input_t = kith_sim_input


class kith_sim_artifact_key(ctypes.Structure):
    pass


kith_sim_artifact_key_t = kith_sim_artifact_key


class kith_sim_artifact(ctypes.Structure):
    pass


kith_sim_artifact_t = kith_sim_artifact


class kith_sim_cell_product(ctypes.Structure):
    pass


kith_sim_cell_product_t = kith_sim_cell_product


class kith_sim_model_vtable(ctypes.Structure):
    pass


kith_sim_model_vtable_t = kith_sim_model_vtable


class kith_sim_format(IntEnum):
    KITH_SIM_ARTIFACT_SHARDS = 16
    KITH_SIM_FIX_SHIFT = 16


class kith_sim_default(IntEnum):
    KITH_SIM_DEFAULT_TICK_HZ = 20
    KITH_SIM_DEFAULT_BUCKET_COUNT = 4096


kith_sim_config._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("base_speed", ctypes.c_uint32),
    ("run_speed", ctypes.c_uint32),
    ("accel", ctypes.c_uint32),
    ("decel", ctypes.c_uint32),
    ("move_eps", ctypes.c_float),
    ("collision_radius", ctypes.c_uint32),
    ("reserved", ctypes.c_void_p * 8),
]

kith_sim_params._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("tick_hz", ctypes.c_uint32),
    ("artifact_bucket_count", ctypes.c_uint32),
    ("reserved", ctypes.c_void_p * 8),
]

kith_sim_actor._fields_ = [
    ("id", ctypes.c_uint64),
    ("pos_x", ctypes.c_int64),
    ("pos_y", ctypes.c_int64),
    ("pos_z", ctypes.c_int64),
    ("vel_x", ctypes.c_int64),
    ("vel_y", ctypes.c_int64),
    ("vel_z", ctypes.c_int64),
    ("input_tick", ctypes.c_uint32),
    ("flags", ctypes.c_uint32),
    ("update_seq", ctypes.c_uint32),
]

kith_sim_input._fields_ = [
    ("input_tick", ctypes.c_uint32),
    ("move_x", ctypes.c_int16),
    ("move_y", ctypes.c_int16),
    ("move_z", ctypes.c_int16),
    ("flags", ctypes.c_uint8),
]

kith_sim_artifact_key._fields_ = [
    ("zone", ctypes.c_uint32),
    ("cell_x", ctypes.c_int32),
    ("cell_y", ctypes.c_int32),
    ("cell_z", ctypes.c_int32),
    ("lod", ctypes.c_uint8),
    ("pad", ctypes.c_uint8 * 3),
    ("authority_epoch", ctypes.c_uint32),
    ("publish_seq", ctypes.c_uint64),
]

kith_sim_artifact._fields_ = [
    ("key", kith_sim_artifact_key_t),
    ("actor_id", ctypes.c_uint64),
    ("pos_x", ctypes.c_int64),
    ("pos_y", ctypes.c_int64),
    ("pos_z", ctypes.c_int64),
    ("vel_x", ctypes.c_int64),
    ("vel_y", ctypes.c_int64),
    ("vel_z", ctypes.c_int64),
    ("input_tick", ctypes.c_uint32),
    ("update_seq", ctypes.c_uint32),
]

kith_sim_cell_product._fields_ = [
    ("zone", ctypes.c_uint32),
    ("cell_x", ctypes.c_int32),
    ("cell_y", ctypes.c_int32),
    ("cell_z", ctypes.c_int32),
    ("lod", ctypes.c_uint8),
    ("pad", ctypes.c_uint8 * 3),
    ("actor_count", ctypes.c_uint32),
    ("latest_publish_seq", ctypes.c_uint64),
    ("authority_epoch", ctypes.c_uint32),
]

kith_sim_model_vtable._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    (
        "init",
        ctypes.CFUNCTYPE(
            ctypes.c_int,
            ctypes.POINTER(kith_sim_config),
            ctypes.POINTER(kith_allocator),
            ctypes.POINTER(ctypes.POINTER(kith_sim_model)),
        ),
    ),
    ("destroy", ctypes.CFUNCTYPE(None, ctypes.POINTER(kith_sim_model))),
    (
        "step",
        ctypes.CFUNCTYPE(
            ctypes.c_int,
            ctypes.POINTER(kith_sim_model),
            ctypes.POINTER(kith_sim_actor),
            ctypes.c_ulong,
            ctypes.c_uint,
        ),
    ),
    (
        "apply_input",
        ctypes.CFUNCTYPE(
            ctypes.c_int,
            ctypes.POINTER(kith_sim_model),
            ctypes.POINTER(kith_sim_actor),
            ctypes.POINTER(kith_sim_input),
        ),
    ),
    (
        "load_behavior",
        ctypes.CFUNCTYPE(ctypes.c_int, ctypes.POINTER(kith_sim_model), ctypes.c_char_p),
    ),
    ("reserved", ctypes.c_void_p * 8),
]

# ---------------------------------------------------------------------------
# function signatures
# ---------------------------------------------------------------------------
_FUNCTIONS: list[tuple[str, object, list[object]]] = [
    (
        "kith_sim_create",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_sim_params_t),
            ctypes.POINTER(kith_allocator_t),
            ctypes.POINTER(ctypes.POINTER(kith_sim_t)),
        ],
    ),
    ("kith_sim_destroy", None, [ctypes.POINTER(kith_sim_t)]),
    (
        "kith_sim_register_model",
        ctypes.c_int,
        [ctypes.POINTER(kith_sim_t), ctypes.c_char_p, ctypes.POINTER(kith_sim_model_vtable_t)],
    ),
    (
        "kith_sim_create_model",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_sim_t),
            ctypes.c_char_p,
            ctypes.POINTER(kith_sim_config_t),
            ctypes.POINTER(kith_allocator_t),
            ctypes.POINTER(ctypes.POINTER(kith_sim_model_t)),
        ],
    ),
    ("kith_sim_model_destroy", None, [ctypes.POINTER(kith_sim_model_t)]),
    (
        "kith_sim_model_step",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_sim_model_t),
            ctypes.POINTER(kith_sim_actor_t),
            ctypes.c_size_t,
            ctypes.c_uint32,
        ],
    ),
    (
        "kith_sim_model_apply_input",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_sim_model_t),
            ctypes.POINTER(kith_sim_actor_t),
            ctypes.POINTER(kith_sim_input_t),
        ],
    ),
    (
        "kith_sim_model_load_behavior",
        ctypes.c_int,
        [ctypes.POINTER(kith_sim_model_t), ctypes.c_char_p],
    ),
    (
        "kith_sim_publish_artifact",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_sim_t),
            ctypes.POINTER(kith_sim_artifact_key_t),
            ctypes.POINTER(kith_sim_actor_t),
            ctypes.POINTER(ctypes.c_uint64),
        ],
    ),
    ("kith_sim_remove_artifact", ctypes.c_int, [ctypes.POINTER(kith_sim_t), ctypes.c_uint64]),
    ("kith_sim_remove_zone", ctypes.c_int, [ctypes.POINTER(kith_sim_t), ctypes.c_uint32]),
    (
        "kith_sim_snapshot_cell",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_sim_t),
            ctypes.POINTER(kith_sim_artifact_key_t),
            ctypes.POINTER(kith_sim_artifact_t),
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_size_t),
        ],
    ),
    (
        "kith_sim_snapshot_zone_cells",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_sim_t),
            ctypes.c_uint32,
            ctypes.c_uint8,
            ctypes.POINTER(kith_sim_cell_product_t),
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_size_t),
        ],
    ),
    (
        "kith_sim_cell_product",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_sim_t),
            ctypes.POINTER(kith_sim_artifact_key_t),
            ctypes.POINTER(kith_sim_cell_product_t),
        ],
    ),
    ("kith_sim_artifact_count", ctypes.c_uint64, [ctypes.POINTER(kith_sim_t)]),
]


def configure(lib: ctypes.CDLL) -> None:
    """Attach argtypes/restype to every KITH_API symbol on `lib`."""
    for name, restype, argtypes in _FUNCTIONS:
        fn = getattr(lib, name)
        fn.restype = restype
        fn.argtypes = argtypes
