# Auto-generated by tools/gen_ctypes.py from:
#   kith/state/state.h
# Regenerate via `python3 tools/gen_ctypes.py`. Do not edit by hand.


from __future__ import annotations

import ctypes
from enum import IntEnum

from kith._generated.reactor import kith_reactor_t
from kith._generated.types import kith_allocator_t


class kith_state(ctypes.Structure):
    pass


kith_state_t = kith_state


class kith_state_params(ctypes.Structure):
    pass


kith_state_params_t = kith_state_params


class kith_state_reply(ctypes.Structure):
    pass


kith_state_reply_t = kith_state_reply


class kith_state_default(IntEnum):
    KITH_STATE_DEFAULT_HOST = 0
    KITH_STATE_DEFAULT_PORT = 6379
    KITH_STATE_DEFAULT_TIMEOUT_MS = 5000


kith_state_reply_fn = ctypes.CFUNCTYPE(None, ctypes.POINTER(kith_state_reply))

kith_state_params._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("host", ctypes.c_char_p),
    ("port", ctypes.c_uint16),
    ("timeout_ms", ctypes.c_uint32),
    ("key_prefix", ctypes.c_char_p),
    ("key_prefix_len", ctypes.c_uint32),
    ("reserved", ctypes.c_void_p * 8),
]

kith_state_reply._fields_ = [
    ("status", ctypes.c_int),
    ("err_str", ctypes.c_char_p),
    ("value", ctypes.c_void_p),
    ("value_len", ctypes.c_size_t),
    ("exists", ctypes.c_bool),
    ("user_data", ctypes.c_void_p),
]

# ---------------------------------------------------------------------------
# function signatures
# ---------------------------------------------------------------------------
_FUNCTIONS: list[tuple[str, object, list[object]]] = [
    (
        "kith_state_create",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_state_params_t),
            ctypes.POINTER(kith_reactor_t),
            ctypes.POINTER(kith_allocator_t),
            ctypes.POINTER(ctypes.POINTER(kith_state_t)),
        ],
    ),
    ("kith_state_destroy", None, [ctypes.POINTER(kith_state_t)]),
    (
        "kith_state_set",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_state_t),
            ctypes.c_void_p,
            ctypes.c_size_t,
            ctypes.c_void_p,
            ctypes.c_size_t,
            kith_state_reply_fn,
            ctypes.c_void_p,
        ],
    ),
    (
        "kith_state_get",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_state_t),
            ctypes.c_void_p,
            ctypes.c_size_t,
            kith_state_reply_fn,
            ctypes.c_void_p,
        ],
    ),
    (
        "kith_state_del",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_state_t),
            ctypes.c_void_p,
            ctypes.c_size_t,
            kith_state_reply_fn,
            ctypes.c_void_p,
        ],
    ),
    (
        "kith_state_exists",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_state_t),
            ctypes.c_void_p,
            ctypes.c_size_t,
            kith_state_reply_fn,
            ctypes.c_void_p,
        ],
    ),
]


def configure(lib: ctypes.CDLL) -> None:
    """Attach argtypes/restype to every KITH_API symbol on `lib`."""
    for name, restype, argtypes in _FUNCTIONS:
        fn = getattr(lib, name)
        fn.restype = restype
        fn.argtypes = argtypes
