# Auto-generated by tools/gen_ctypes.py from:
#   kith/types.h
# Regenerate via `python3 tools/gen_ctypes.py`. Do not edit by hand.


from __future__ import annotations

import ctypes
from enum import IntEnum


class kith_allocator(ctypes.Structure):
    pass


kith_allocator_t = kith_allocator


class kith_error(IntEnum):
    KITH_OK = 0
    KITH_EINVAL = 1
    KITH_ENOMEM = 2
    KITH_ENOSYS = 3
    KITH_ENOENT = 4
    KITH_EEXIST = 5
    KITH_EBUSY = 6
    KITH_EAGAIN = 7
    KITH_EPERM = 8
    KITH_ERANGE = 9
    KITH_EOVERFLOW = 10
    KITH_EFAULT = 11
    KITH_EIO = 12
    KITH_ETIMEDOUT = 13
    KITH_ECONNRESET = 14
    KITH_ESHUTDOWN = 15
    KITH_ESTATE = 16
    KITH_EPROTO = 17
    KITH_ESIZE = 18
    KITH_EABIVER = 19
    KITH_EUSER = 10000


kith_error_t = kith_error

kith_alloc_fn = ctypes.CFUNCTYPE(ctypes.c_void_p, ctypes.c_void_p, ctypes.c_ulong)

kith_alloc_zero_fn = ctypes.CFUNCTYPE(
    ctypes.c_void_p, ctypes.c_void_p, ctypes.c_ulong, ctypes.c_ulong
)

kith_realloc_fn = ctypes.CFUNCTYPE(
    ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_ulong
)

kith_free_fn = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_void_p)

kith_allocator._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("user_data", ctypes.c_void_p),
    ("alloc", kith_alloc_fn),
    ("alloc_zero", kith_alloc_zero_fn),
    ("realloc", kith_realloc_fn),
    ("free", kith_free_fn),
    ("reserved", ctypes.c_void_p * 8),
]


def configure(lib: ctypes.CDLL) -> None:
    """No KITH_API functions in this module."""
    _ = lib
