# Auto-generated by tools/gen_ctypes.py from:
#   kith/util/rng.h
#   kith/util/tick_clock.h
#   kith/util/util.h
#   kith/util/wall_clock.h
# Regenerate via `python3 tools/gen_ctypes.py`. Do not edit by hand.


from __future__ import annotations

import ctypes

from kith._generated.types import kith_allocator_t


class kith_rng(ctypes.Structure):
    pass


kith_rng_t = kith_rng


class kith_rng_params(ctypes.Structure):
    pass


kith_rng_params_t = kith_rng_params


class kith_rng_state(ctypes.Structure):
    pass


kith_rng_state_t = kith_rng_state


class kith_tick_clock(ctypes.Structure):
    pass


kith_tick_clock_t = kith_tick_clock


class kith_tick_clock_params(ctypes.Structure):
    pass


kith_tick_clock_params_t = kith_tick_clock_params

kith_rng_params._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("seed", ctypes.c_uint64),
    ("reserved", ctypes.c_void_p * 8),
]

kith_rng_state._fields_ = [
    ("derivation_seed", ctypes.c_uint64),
    ("words", ctypes.c_uint64 * 4),
]

kith_tick_clock_params._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("initial_tick", ctypes.c_uint64),
    ("tick_hz", ctypes.c_uint32),
    ("reserved", ctypes.c_void_p * 8),
]

# ---------------------------------------------------------------------------
# function signatures
# ---------------------------------------------------------------------------
_FUNCTIONS: list[tuple[str, object, list[object]]] = [
    (
        "kith_rng_create",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_rng_params_t),
            ctypes.POINTER(kith_allocator_t),
            ctypes.POINTER(ctypes.POINTER(kith_rng_t)),
        ],
    ),
    ("kith_rng_destroy", None, [ctypes.POINTER(kith_rng_t)]),
    (
        "kith_rng_create_stream",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_rng_t),
            ctypes.c_uint64,
            ctypes.POINTER(kith_allocator_t),
            ctypes.POINTER(ctypes.POINTER(kith_rng_t)),
        ],
    ),
    ("kith_rng_next", ctypes.c_uint64, [ctypes.POINTER(kith_rng_t)]),
    ("kith_rng_next_below", ctypes.c_uint64, [ctypes.POINTER(kith_rng_t), ctypes.c_uint64]),
    ("kith_rng_next_unit", ctypes.c_double, [ctypes.POINTER(kith_rng_t)]),
    ("kith_rng_derivation_seed", ctypes.c_uint64, [ctypes.POINTER(kith_rng_t)]),
    (
        "kith_rng_state_save",
        ctypes.c_int,
        [ctypes.POINTER(kith_rng_t), ctypes.POINTER(kith_rng_state_t)],
    ),
    (
        "kith_rng_state_restore",
        ctypes.c_int,
        [ctypes.POINTER(kith_rng_t), ctypes.POINTER(kith_rng_state_t)],
    ),
    (
        "kith_tick_clock_create",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_tick_clock_params_t),
            ctypes.POINTER(kith_allocator_t),
            ctypes.POINTER(ctypes.POINTER(kith_tick_clock_t)),
        ],
    ),
    ("kith_tick_clock_destroy", None, [ctypes.POINTER(kith_tick_clock_t)]),
    ("kith_tick_clock_advance", ctypes.c_int, [ctypes.POINTER(kith_tick_clock_t), ctypes.c_uint64]),
    ("kith_tick_clock_reset", ctypes.c_int, [ctypes.POINTER(kith_tick_clock_t), ctypes.c_uint64]),
    ("kith_tick_clock_tick", ctypes.c_uint64, [ctypes.POINTER(kith_tick_clock_t)]),
    (
        "kith_tick_clock_elapsed_ms",
        ctypes.c_int,
        [ctypes.POINTER(kith_tick_clock_t), ctypes.POINTER(ctypes.c_uint64)],
    ),
    (
        "kith_tick_clock_elapsed_ns",
        ctypes.c_int,
        [ctypes.POINTER(kith_tick_clock_t), ctypes.POINTER(ctypes.c_uint64)],
    ),
    ("kith_version_string", ctypes.c_char_p, []),
    ("kith_version_abi", ctypes.c_uint, []),
    ("kith_python_finalizing_set", None, [ctypes.c_int]),
    ("kith_python_finalizing", ctypes.c_int, []),
    ("kith_python_note_handler_exception", None, []),
    ("kith_python_handler_exceptions", ctypes.c_uint64, []),
    ("kith_wall_clock_ns", ctypes.c_uint64, []),
]


def configure(lib: ctypes.CDLL) -> None:
    """Attach argtypes/restype to every KITH_API symbol on `lib`."""
    for name, restype, argtypes in _FUNCTIONS:
        fn = getattr(lib, name)
        fn.restype = restype
        fn.argtypes = argtypes
