# Auto-generated by tools/gen_ctypes.py from:
#   kith/version.h
# Regenerate via `python3 tools/gen_ctypes.py`. Do not edit by hand.


from __future__ import annotations

import ctypes


# ---------------------------------------------------------------------------
# macro constants
# ---------------------------------------------------------------------------
KITH_VERSION_MAJOR = 1
KITH_VERSION_MINOR = 0
KITH_VERSION_PATCH = 0
KITH_VERSION_STRING = "1.0.0"
KITH_ABI_VERSION = 1


def configure(lib: ctypes.CDLL) -> None:
    """No KITH_API functions in this module."""
    _ = lib
