# Auto-generated by tools/gen_ctypes.py from:
#   kith/worker/worker.h
# Regenerate via `python3 tools/gen_ctypes.py`. Do not edit by hand.


from __future__ import annotations

import ctypes
from enum import IntEnum

from kith._generated.types import kith_allocator_t


class kith_worker(ctypes.Structure):
    pass


kith_worker_t = kith_worker


class kith_worker_params(ctypes.Structure):
    pass


kith_worker_params_t = kith_worker_params


class kith_worker_bridge(ctypes.Structure):
    pass


kith_worker_bridge_t = kith_worker_bridge


class kith_worker_default(IntEnum):
    KITH_WORKER_DEFAULT_WORKER_COUNT = 1
    KITH_WORKER_DEFAULT_TASK_CAPACITY = 4096


kith_worker_task_cb = ctypes.CFUNCTYPE(None, ctypes.c_void_p)

kith_worker_ready_fn = ctypes.CFUNCTYPE(None, ctypes.c_int, ctypes.c_uint, ctypes.c_void_p)

kith_worker_params._fields_ = [
    ("size", ctypes.c_uint32),
    ("abi_version", ctypes.c_uint32),
    ("worker_count", ctypes.c_uint32),
    ("task_capacity", ctypes.c_uint32),
    ("reserved", ctypes.c_void_p * 8),
]

# ---------------------------------------------------------------------------
# function signatures
# ---------------------------------------------------------------------------
_FUNCTIONS: list[tuple[str, object, list[object]]] = [
    (
        "kith_worker_create",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_worker_params_t),
            ctypes.POINTER(kith_allocator_t),
            ctypes.POINTER(ctypes.POINTER(kith_worker_t)),
        ],
    ),
    ("kith_worker_destroy", None, [ctypes.POINTER(kith_worker_t)]),
    (
        "kith_worker_submit",
        ctypes.c_int,
        [ctypes.POINTER(kith_worker_t), kith_worker_task_cb, ctypes.c_void_p],
    ),
    ("kith_worker_count", ctypes.c_uint32, [ctypes.POINTER(kith_worker_t)]),
    ("kith_worker_tasks_submitted", ctypes.c_uint64, [ctypes.POINTER(kith_worker_t)]),
    ("kith_worker_tasks_completed", ctypes.c_uint64, [ctypes.POINTER(kith_worker_t)]),
    (
        "kith_worker_bridge_create_ready",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_worker_t),
            kith_worker_ready_fn,
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.POINTER(kith_worker_bridge_t)),
        ],
    ),
    (
        "kith_worker_bridge_create_task",
        ctypes.c_int,
        [
            ctypes.POINTER(kith_worker_t),
            kith_worker_task_cb,
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.POINTER(kith_worker_bridge_t)),
        ],
    ),
    ("kith_worker_bridge_destroy", None, [ctypes.POINTER(kith_worker_bridge_t)]),
    ("kith_worker_bridge_ready_cb", None, [ctypes.c_int, ctypes.c_uint, ctypes.c_void_p]),
    ("kith_worker_bridge_task_cb", None, [ctypes.c_void_p]),
]


def configure(lib: ctypes.CDLL) -> None:
    """Attach argtypes/restype to every KITH_API symbol on `lib`."""
    for name, restype, argtypes in _FUNCTIONS:
        fn = getattr(lib, name)
        fn.restype = restype
        fn.argtypes = argtypes
